ext {
    artifactId = 'async-kafka-apicurio'
    artifactDescription = 'Async Kafka Apicurio Schema Validation'
}

dependencies {
    api project(':async-kafka')
    api 'io.apicurio:apicurio-registry-schema-resolver:3.3.2'
    api 'io.apicurio:apicurio-registry-serde-common:3.3.2'
    api 'io.apicurio:apicurio-registry-serde-kafka-common:3.3.2'
    api 'io.apicurio:apicurio-registry-serde-common-jsonschema:3.3.2'
}
